name: Build and push (Drupal 9.5 + PHP 8.1)
on:
  schedule:
    - cron: '00 1 * * *'
  push:
    branches:
jobs:
  deploy:
    uses: ./.github/workflows/build-push.yml
    with:
      drupal_version: 9.5
      php_version: 8.1
    permissions:
      contents: read
      id-token: write
    secrets: inherit
